### ISSUE TITLE
Solution Branch lists a failing solution

### ISSUE THREAD

**Issue by mkirby** [learn-co-curriculum/sql-table-relations-library-lab#2]
I don't think the last test on the last method is descriptive enough. It talks about the number of books they have appeared in, in descending order but does not mention that names also need to be in ascending order. **This is also not reflected in the solution code, which fails to pass the provided test.** 

Method Description:
```
def
select_character_names_and_number_of_books_they_are_in 
end
```
Test Description:
```
it 'selects all of the character names and their number of books they have appeared in, in descending order, grouped by character name'
```
Failing Solution:
```
  <<-SQL
    SELECT characters.name, COUNT(*) as book_count 
    FROM character_books 
    JOIN characters 
    ON character_books.character_id = characters.id 
    GROUP BY characters.name 
    ORDER BY book_count DESC
  SQL
```
Passing Solution Suggestion:
```
 <<-SQL
    SELECT characters.name, COUNT(*) AS book_count
    FROM character_books
    JOIN characters
    ON character_books.character_id = characters.id
    GROUP BY characters.name
    ORDER BY book_count DESC, characters.name
SQL
```

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
